export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_DETAIL_REQUEST = "FETCH_MOVIES_DETAIL_REQUEST";
export const FETCH_MOVIES_DETAIL_SUCCESS = "FETCH_MOVIES_DETAIL_SUCCESS";
export const FETCH_MOVIES_DETAIL_FAILED = "FETCH_MOVIES_DETAIL_FAILED";

